spring:
  datasource:
    url: jdbc:postgresql://13.209.4.239:5432/gillait
    username: root
    password: gillaIT0229
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate