spring:
  datasource:
    url: jdbc:postgresql://13.209.4.239:5432/gillait
    username: root
    password: gillaIT0229
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: gillait.official@gmail.com
    password: qntjlpyppwxrbwwd
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true